// Auto-instrumentation for Next.js server log capture

import * as fs from 'fs';
import * as path from 'path';

const INSTRUMENTATION_CONTENT = `// Auto-generated by react-recall for server log capture
export async function register() {
  if (process.env.NODE_ENV === 'development') {
    await import('react-recall/server')
  }
}
`;

/**
 * Detects if the current directory is a Next.js project
 */
export function detectNextJs(workingDir: string): boolean {
  // Check for next.config.* files
  const configFiles = [
    'next.config.js',
    'next.config.mjs',
    'next.config.ts',
  ];

  for (const configFile of configFiles) {
    if (fs.existsSync(path.join(workingDir, configFile))) {
      return true;
    }
  }

  // Check package.json for next dependency
  const packageJsonPath = path.join(workingDir, 'package.json');
  if (fs.existsSync(packageJsonPath)) {
    try {
      const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf-8'));
      const deps = {
        ...packageJson.dependencies,
        ...packageJson.devDependencies,
      };
      if (deps && deps.next) {
        return true;
      }
    } catch {
      // Ignore parse errors
    }
  }

  return false;
}

/**
 * Finds the correct path for instrumentation.ts
 * Next.js looks for it in project root or src/ directory
 */
function findInstrumentationPath(workingDir: string): string {
  // Check if src/ directory exists (common Next.js pattern)
  const srcDir = path.join(workingDir, 'src');
  if (fs.existsSync(srcDir) && fs.statSync(srcDir).isDirectory()) {
    // Check if there's already an instrumentation file in src/
    const srcInstrumentationTs = path.join(srcDir, 'instrumentation.ts');
    const srcInstrumentationJs = path.join(srcDir, 'instrumentation.js');
    if (fs.existsSync(srcInstrumentationTs) || fs.existsSync(srcInstrumentationJs)) {
      return srcInstrumentationTs;
    }
  }

  // Default to project root
  return path.join(workingDir, 'instrumentation.ts');
}

/**
 * Attempts to auto-instrument a Next.js project
 * Returns true if successful, false if manual setup is needed
 */
export function autoInstrument(workingDir: string): { success: boolean; message: string } {
  const instrumentationPath = findInstrumentationPath(workingDir);

  // Check if file already exists
  const tsPath = instrumentationPath;
  const jsPath = instrumentationPath.replace('.ts', '.js');

  if (fs.existsSync(tsPath)) {
    const content = fs.readFileSync(tsPath, 'utf-8');
    if (content.includes('react-recall/server')) {
      return {
        success: true,
        message: 'Server log capture already configured in instrumentation.ts',
      };
    }
    return {
      success: false,
      message: `instrumentation.ts already exists but doesn't include react-recall/server.\nPlease add: await import('react-recall/server') to your register() function.`,
    };
  }

  if (fs.existsSync(jsPath)) {
    const content = fs.readFileSync(jsPath, 'utf-8');
    if (content.includes('react-recall/server')) {
      return {
        success: true,
        message: 'Server log capture already configured in instrumentation.js',
      };
    }
    return {
      success: false,
      message: `instrumentation.js already exists but doesn't include react-recall/server.\nPlease add: await import('react-recall/server') to your register() function.`,
    };
  }

  // Create the instrumentation file
  try {
    fs.writeFileSync(tsPath, INSTRUMENTATION_CONTENT);
    return {
      success: true,
      message: `Created ${path.relative(workingDir, tsPath)} for server log capture`,
    };
  } catch (err) {
    return {
      success: false,
      message: `Failed to create instrumentation.ts: ${err}`,
    };
  }
}

/**
 * Prints manual setup instructions
 */
export function printManualInstructions(): void {
  console.log(`
To capture server logs, add the following to your project:

  Next.js: Create instrumentation.ts in your project root (or src/):

    // instrumentation.ts
    export async function register() {
      if (process.env.NODE_ENV === 'development') {
        await import('react-recall/server')
      }
    }

  Other frameworks (Express, Fastify, etc.): Add to the top of your server entry file:

    // server.js or app.js
    import 'react-recall/server'

Then restart your dev server.
`);
}
